# Testing

## Testing: District

```{r results='hide'}
mD <- ulam(
    alist(
        C ~ bernoulli(p),
        logit(p) <- a[D],
        transpars> vector[61]:a <<- abar + zA*sA,
        abar ~ normal(0, 1),
        vector[61]:zA ~ normal(0,1),
        sA ~ exponential(1)
    ),
    data = dat.2,
    cores = 4, chains = 4,
    log_lik = TRUE,
    file = "m.district"
)
```

### Effect

```{r}
ps.mD <- extract.samples(mD)
```

```{r fig.width=15, fig.height=5}
abar <- inv_logit(ps.mD$abar)
abar.df <- as_tibble(abar) %>%
    pivot_longer(everything()) %>%
    group_by(name) %>%
    group_modify(~ with(density(.x$value), tibble(x,y))) %>%
    mutate(mean = mean(x),
           lhpdi = HPDI(x)[1],
           hhpdi = HPDI(x)[2])


alpha <- inv_logit(ps.mD$a)
dimnames(alpha)[[2]] <- 1:61

alpha.df <- as_tibble(alpha) %>%
    pivot_longer(everything()) %>%
    group_by(name) %>%
    group_modify(~ with(density(.x$value), tibble(x,y))) %>%
    mutate(mean = mean(x),
           lhpdi = HPDI(x)[1],
           hhpdi = HPDI(x)[2])

alpha.df %>%
    ggplot(aes(y=mean, x=as.numeric(name))) +
    geom_pointrange(aes(ymin=lhpdi, ymax=hhpdi), color = 2) +
    geom_point(aes(x=district, y=prop.contraception, size=W), shape=1, data=contraception.df) +
    geom_rug(x=54, sides = "b") +
    geom_hline(yintercept = 0.367) +
    ylab("probability of use of contraceptives") +
    xlab("district") +
    labs(title="Posterior distribution of probabilities of use of contraceptives per district",
         subtitle = "Open points represent the real data, scaled by population size")
```

## Testing: Urbanization

```{r results='hide'}
mU <- ulam(
    alist(
        C ~ bernoulli(p),
        logit(p) <- b[U],
        transpars> vector[2]:b <<- bbar + zB*sB,
        bbar ~ normal(0, 1),
        vector[2]:zB ~ normal(0,1),
        sB ~ exponential(1)
    ),
    data = dat.2,
    cores = 4, chains = 4,
    log_lik = TRUE,
    file = "m.urban"
)
```

### Effect

```{r}
ps.mU <- extract.samples(mU)
```

```{r fig.width=15, fig.height=5}
bbar <- inv_logit(ps.mU$bbar)
bbar.df <- as_tibble(bbar) %>%
    pivot_longer(everything()) %>%
    group_by(name) %>%
    group_modify(~ with(density(.x$value), tibble(x,y))) %>%
    mutate(mean = mean(x),
           lhpdi = HPDI(x)[1],
           hhpdi = HPDI(x)[2])


beta <- inv_logit(ps.mU$b)
dimnames(beta)[[2]] <- c("rural", "urban")

beta.df <- as_tibble(beta) %>%
    pivot_longer(everything()) %>%
    group_by(name) %>%
    group_modify(~ with(density(.x$value), tibble(x,y))) %>%
    mutate(mean = mean(x),
           lhpdi = HPDI(x)[1],
           hhpdi = HPDI(x)[2])

beta.df %>%
    ggplot(aes(x=x, y=y, color=name, fill=name)) +
    geom_line() +
    geom_area(data=subset(beta.df, x > lhpdi & x < hhpdi),  alpha = 0.2)
```


## Testing: District and Urbanization

```{r results='hide'}
mUDa <- ulam(
    alist(
        C ~ bernoulli(p),
        logit(p) <- a[D] + b[U],
        transpars> vector[2]:b <<- bbar + zB*sB,
        bbar ~ normal(0, 1),
        vector[2]:zB ~ normal(0,1),
        sB ~ exponential(1),
        transpars> vector[61]:a <<- abar + zA*sA,
        abar ~ normal(0, 1),
        vector[61]:zA ~ normal(0,1),
        sA ~ exponential(1)
    ),
    data = dat.2,
    cores = 4, chains = 4,
    log_lik = TRUE,
    file = "m.ud.indep"
)
```

### Effect

```{r}
ps.mUD <- extract.samples(mUDa)
```

```{r fig.width=15, fig.height=5}
alpha <- inv_logit(ps.mUD$a)

alpha.lhpdi <- apply(alpha,2,HPDI)["|0.89",]
alpha.hhpdi <- apply(alpha,2,HPDI)["0.89|",]
alpha.mean <- apply(alpha,2,mean)

alpha.df <- tibble(
    lhpdi = alpha.lhpdi,
    hhpdi = alpha.hhpdi,
    mean = alpha.mean,
    district = 1:61
)

alpha.df %>%
    ggplot(aes(y=mean, x=as.numeric(district))) +
    geom_pointrange(aes(ymin=lhpdi, ymax=hhpdi), color = 2) +
    geom_point(aes(x=district, y=prop.contraception, size=W), shape=1, data=district.df, na.rm = TRUE) +
    geom_rug(x=54, sides = "b") +
    geom_hline(yintercept = 0.367) +
    ylab("probability of use of contraceptives") +
    xlab("district") +
    labs(title="Posterior distribution of probabilities of use of contraceptives per district",
         subtitle = "Open points represent the real data, scaled by population size")
```



```{r fig.width=5, fig.height=5}
beta <- inv_logit(ps.mUD$b)
beta.lhpdi <- apply(beta,2,HPDI)["|0.89",]
beta.hhpdi <- apply(beta,2,HPDI)["0.89|",]
beta.mean <- apply(beta,2,mean)


beta.df <- tibble(
    urban = c('rural', 'urban'),
    lhpdi = beta.lhpdi,
    hhpdi = beta.hhpdi,
    mean = beta.mean,
)

beta.df %>% 
    ggplot(aes(y=mean, x=urban)) +
    geom_pointrange(aes(ymin=lhpdi, ymax=hhpdi, color=urban), size=1.2, shape=21, fill='white') +
    ylab("posterior distribution of β_j (prob)") +
    labs(title="Use of contraceptives by urbanicity")
```

## Testing: District and Urbanization (matrix)

```{r results='hide'}
mUDb <- ulam(
    alist(
        C ~ bernoulli(p),
        logit(p) <- a[D] + b[D,U],
        transpars> matrix[61,2]:b <<- bbar + zB*sB,
        bbar ~ normal(0, 1),
        matrix[61,2]:zB ~ normal(0,1),
        sB ~ exponential(1),
        transpars> vector[61]:a <<- abar + zA*sA,
        abar ~ normal(0, 1),
        vector[61]:zA ~ normal(0,1),
        sA ~ exponential(1)
    ),
    data = dat.2,
    cores = 4, chains = 4,
    log_lik = TRUE,
    file = "m.ud.matrix"
)
```

### Effect

```{r}
ps.mUD <- extract.samples(mUDb)
```

```{r fig.width=15, fig.height=5}
alpha <- inv_logit(ps.mUD$a)

alpha.lhpdi <- apply(alpha,2,HPDI)["|0.89",]
alpha.hhpdi <- apply(alpha,2,HPDI)["0.89|",]
alpha.mean <- apply(alpha,2,mean)

alpha.df <- tibble(
    lhpdi = alpha.lhpdi,
    hhpdi = alpha.hhpdi,
    mean = alpha.mean,
    district = 1:61
)

alpha.df %>%
    ggplot(aes(y=mean, x=as.numeric(district))) +
    geom_pointrange(aes(ymin=lhpdi, ymax=hhpdi), color = 2) +
    geom_point(aes(x=district, y=prop.contraception, size=W), shape=1, data=contraception.df) +
    geom_rug(x=54, sides = "b") +
    geom_hline(yintercept = 0.367) +
    ylab("probability of use of contraceptives") +
    xlab("district") +
    labs(title="Posterior distribution of probabilities of use of contraceptives per district",
         subtitle = "Open points represent the real data, scaled by population size")
```



```{r fig.width=15, fig.height=10}
beta <- inv_logit(ps.mUD$b)
dimnames(beta)[[3]] <- c("rural", "urban")

beta.lhpdi <- c(apply(beta,c(2,3),HPDI)["|0.89",,"rural"],apply(beta,c(2,3),HPDI)["|0.89",,"urban"])
beta.hhpdi <- c(apply(beta,c(2,3),HPDI)["0.89|",,"rural"],apply(beta,c(2,3),HPDI)["0.89|",,"urban"])
beta.mean <- c(apply(beta,c(2,3),mean)[,"rural"],apply(beta,c(2,3),mean)[,"urban"])

beta.df <- tibble(
    lhpdi = beta.lhpdi,
    hhpdi = beta.hhpdi,
    mean = beta.mean,
    district = rep(1:61,2),
    urban = c(rep("rural", 61), rep("urban", 61))
)

beta.df %>% 
    ggplot(aes(y=mean, x=as.numeric(district))) +
    geom_pointrange(aes(ymin=lhpdi, ymax=hhpdi, color=urban), size=1.2, shape=21, fill='white') +
    geom_line(aes(x=as.numeric(district), y=mean), data=alpha.df) +
    facet_wrap(~ urban, nrow=2) +
    xlab("district") + ylab("posterior distribution of β_jk (prob)") +
    labs(title="Posterior distribution of probabilities of use of contraceptives per district and urbanicity",
         subtitle="Dashed line corresponding to avarage predicted use of contraceptives in the district")
```

```{r fig.width=15, fig.height=5}
beta.diff <- beta[,,2] - beta[,,1]

beta.diff.mean <- apply(beta.diff,2,mean)
beta.diff.lhpdi <- apply(beta.diff,2,HPDI)["|0.89",]
beta.diff.hhpdi <- apply(beta.diff,2,HPDI)["0.89|",]

b.diff.df <- tibble(
    district = 1:61,
    mean = beta.diff.mean,
    lhpdi = beta.diff.lhpdi,
    hhpdi = beta.diff.hhpdi,
    prop.urban = district.df$prop.urban,
    )

b.diff.df %>%
    ggplot(aes(y=mean, x=as.numeric(district))) +
    geom_pointrange(aes(ymin=lhpdi, ymax=hhpdi, color=prop.urban), size=1.3, shape = 21, fill="white") +
    geom_hline(yintercept = 0, linetype=2) +
    ylab("difference of use of contraceptives (U-R)") +
    xlab("district") +
    labs(title="Contrast of use of contraceptives per district") +
    scale_color_viridis_c("Proportion of urban living women")
```

## Testing: District and Urbanization (corr-matrix)

```{r results='hide'}
mUDc <- ulam(
    alist(
        C ~ bernoulli(p),
        logit(p) <- a[D] + g[U] + b[D,U],
        transpars> matrix[61,2]:b <<- bbar + zB*sB,
        bbar ~ normal(0, 1),
        matrix[61,2]:zB ~ normal(0,1),
        sB ~ exponential(1),
        transpars> vector[2]:g <<-zG*sG,
        vector[2]:zG ~ normal(0,1),
        sG ~ exponential(1),
        transpars> vector[61]:a <<- abar + zA*sA,
        abar ~ normal(0, 1),
        vector[61]:zA ~ normal(0,1),
        sA ~ exponential(1)
    ),
    data = dat.2,
    cores = 4, chains = 4,
    log_lik = TRUE,
    # file = "m.ud.cormatrix"
)
```

### Effect

```{r}
ps.mUD <- extract.samples(mUDc)
```

```{r fig.width=15, fig.height=5}
alpha <- inv_logit(ps.mUD$a)

alpha.lhpdi <- apply(alpha,2,HPDI)["|0.89",]
alpha.hhpdi <- apply(alpha,2,HPDI)["0.89|",]
alpha.mean <- apply(alpha,2,mean)

alpha.df <- tibble(
    lhpdi = alpha.lhpdi,
    hhpdi = alpha.hhpdi,
    mean = alpha.mean,
    district = 1:61
)

alpha.df %>%
    ggplot(aes(y=mean, x=as.numeric(district))) +
    geom_pointrange(aes(ymin=lhpdi, ymax=hhpdi), color = 2) +
    geom_point(aes(x=district, y=prop.contraception, size=W), shape=1, data=contraception.df) +
    geom_rug(x=54, sides = "b") +
    geom_hline(yintercept = 0.367) +
    ylab("probability of use of contraceptives") +
    xlab("district") +
    labs(title="Posterior distribution of probabilities of use of contraceptives per district",
         subtitle = "Open points represent the real data, scaled by population size")
```



```{r fig.width=15, fig.height=10}
beta <- inv_logit(ps.mUD$b)
dimnames(beta)[[3]] <- c("rural", "urban")

beta.lhpdi <- c(apply(beta,c(2,3),HPDI)["|0.89",,"rural"],apply(beta,c(2,3),HPDI)["|0.89",,"urban"])
beta.hhpdi <- c(apply(beta,c(2,3),HPDI)["0.89|",,"rural"],apply(beta,c(2,3),HPDI)["0.89|",,"urban"])
beta.mean <- c(apply(beta,c(2,3),mean)[,"rural"],apply(beta,c(2,3),mean)[,"urban"])

beta.df <- tibble(
    lhpdi = beta.lhpdi,
    hhpdi = beta.hhpdi,
    mean = beta.mean,
    district = rep(1:61,2),
    urban = c(rep("rural", 61), rep("urban", 61))
)

beta.df %>% 
    ggplot(aes(y=mean, x=as.numeric(district))) +
    geom_pointrange(aes(ymin=lhpdi, ymax=hhpdi, color=urban), size=1.2, shape=21, fill='white') +
    geom_line(aes(x=as.numeric(district), y=mean), data=alpha.df) +
    facet_wrap(~ urban, nrow=2) +
    xlab("district") + ylab("posterior distribution of β_jk (prob)") +
    labs(title="Posterior distribution of probabilities of use of contraceptives per district and urbanicity",
         subtitle="Dashed line corresponding to avarage predicted use of contraceptives in the district")
```

```{r fig.width=15, fig.height=5}
beta.diff <- beta[,,2] - beta[,,1]

beta.diff.mean <- apply(beta.diff,2,mean)
beta.diff.lhpdi <- apply(beta.diff,2,HPDI)["|0.89",]
beta.diff.hhpdi <- apply(beta.diff,2,HPDI)["0.89|",]

b.diff.df <- tibble(
    district = 1:61,
    mean = beta.diff.mean,
    lhpdi = beta.diff.lhpdi,
    hhpdi = beta.diff.hhpdi,
    prop.urban = district.df$prop.urban,
    )

b.diff.df %>%
    ggplot(aes(y=mean, x=as.numeric(district))) +
    geom_pointrange(aes(ymin=lhpdi, ymax=hhpdi, color=prop.urban), size=1.3, shape = 21, fill="white") +
    geom_hline(yintercept = 0, linetype=2) +
    ylab("difference of use of contraceptives (U-R)") +
    xlab("district") +
    labs(title="Contrast of use of contraceptives per district") +
    scale_color_viridis_c("Proportion of urban living women")
```

## Testing: District and Urbanization (corr-matrix 2)

```{r results='hide'}
dat.3 <- as.list(dat.2)
dat.3$N_districts <- 61

mUDe <- ulam(
    alist(
        C ~ bernoulli(p),
        logit(p) <- a[D] + bbar[U] + b[D,U],
        
        # adpatative
        transpars> matrix[N_districts,2]:b <- compose_noncentered(rep_vector(sigma_B, 2), L_Rho_B, zB),
        matrix[2,N_districts]:zB ~ normal(0,1),
        transpars> vector[61]:a <<- abar + zA*sA,
        vector[2]:bbar ~ normal(0, tau_B),
        
        # fixed
        tau_B ~ exponential(1),
        abar ~ normal(0, 1),
        vector[61]:zA ~ normal(0,1),
        sA ~ exponential(1),
        sigma_B ~ exponential(1),
        cholesky_factor_corr[2]:L_Rho_B ~ lkj_corr_cholesky(2),
        
        gq> matrix[2,2]:Rho_B <<- Chol_to_Corr(L_Rho_B)
    ),
    data = dat.3,
    cores = 4, chains = 4,
    log_lik = TRUE,
    # file = "m.ud.cormatrix"
)
```

### Effect

```{r}
ps.mUD <- extract.samples(mUDd)
```

```{r fig.width=15, fig.height=5}
alpha <- inv_logit(ps.mUD$a)

alpha.lhpdi <- apply(alpha,2,HPDI)["|0.89",]
alpha.hhpdi <- apply(alpha,2,HPDI)["0.89|",]
alpha.mean <- apply(alpha,2,mean)

alpha.df <- tibble(
    lhpdi = alpha.lhpdi,
    hhpdi = alpha.hhpdi,
    mean = alpha.mean,
    district = 1:61
)

alpha.df %>%
    ggplot(aes(y=mean, x=as.numeric(district))) +
    geom_pointrange(aes(ymin=lhpdi, ymax=hhpdi), color = 2) +
    geom_point(aes(x=district, y=prop.contraception, size=W), shape=1, data=contraception.df) +
    geom_rug(x=54, sides = "b") +
    geom_hline(yintercept = 0.367) +
    ylab("probability of use of contraceptives") +
    xlab("district") +
    labs(title="Posterior distribution of probabilities of use of contraceptives per district",
         subtitle = "Open points represent the real data, scaled by population size")
```



```{r fig.width=15, fig.height=10}
beta <- inv_logit(ps.mUD$b)
dimnames(beta)[[3]] <- c("rural", "urban")

beta.lhpdi <- c(apply(beta,c(2,3),HPDI)["|0.89",,"rural"],apply(beta,c(2,3),HPDI)["|0.89",,"urban"])
beta.hhpdi <- c(apply(beta,c(2,3),HPDI)["0.89|",,"rural"],apply(beta,c(2,3),HPDI)["0.89|",,"urban"])
beta.mean <- c(apply(beta,c(2,3),mean)[,"rural"],apply(beta,c(2,3),mean)[,"urban"])

beta.df <- tibble(
    lhpdi = beta.lhpdi,
    hhpdi = beta.hhpdi,
    mean = beta.mean,
    district = rep(1:61,2),
    urban = c(rep("rural", 61), rep("urban", 61))
)

beta.df %>% 
    ggplot(aes(y=mean, x=as.numeric(district))) +
    geom_pointrange(aes(ymin=lhpdi, ymax=hhpdi, color=urban), size=1.2, shape=21, fill='white') +
    geom_line(aes(x=as.numeric(district), y=mean), data=alpha.df) +
    facet_wrap(~ urban, nrow=2) +
    xlab("district") + ylab("posterior distribution of β_jk (prob)") +
    labs(title="Posterior distribution of probabilities of use of contraceptives per district and urbanicity",
         subtitle="Dashed line corresponding to avarage predicted use of contraceptives in the district")
```

```{r fig.width=15, fig.height=5}
beta.diff <- beta[,,2] - beta[,,1]

beta.diff.mean <- apply(beta.diff,2,mean)
beta.diff.lhpdi <- apply(beta.diff,2,HPDI)["|0.89",]
beta.diff.hhpdi <- apply(beta.diff,2,HPDI)["0.89|",]

b.diff.df <- tibble(
    district = 1:61,
    mean = beta.diff.mean,
    lhpdi = beta.diff.lhpdi,
    hhpdi = beta.diff.hhpdi,
    prop.urban = district.df$prop.urban,
    )

b.diff.df %>%
    ggplot(aes(y=mean, x=as.numeric(district))) +
    geom_pointrange(aes(ymin=lhpdi, ymax=hhpdi, color=prop.urban), size=1.3, shape = 21, fill="white") +
    geom_hline(yintercept = 0, linetype=2) +
    ylab("difference of use of contraceptives (U-R)") +
    xlab("district") +
    labs(title="Contrast of use of contraceptives per district") +
    scale_color_viridis_c("Proportion of urban living women")
```